### ISSUE TITLE
Corrección Proyecto. Fase: UT2.  Casos de Uso

### ISSUE THREAD

**Issue by jlr2** [perezrecjorge/proyectopsp-grupo2#3]
**REVISION: habéis realizado correcciones pedidas. El principal error que observo es que la descripción de los casos de usos no es congruente con el diagrama. Por otro lado, las relaciones extends deben aparecer en la descripción.**

**CU Inicio de Sesión.** 
- [x] En la precondición sobra "Introducir Datos ...". Este paso debería ir en el Curso Normal.   **CORREGIDO**
- [x] Numerar los pasos en el curso normal para identficar cada uno de ellos y corresponderlos con las alternativas (tb con numeración). Esto se aplica a todos los CU. **CORREGIDO**
- [x] No entiendo la postcondición "El usuario debe tener permisos de administrador". ¿No es mejor indicar que la condición posterior es que el usuario ha iniciado  sesión? **CORREGIDO** 
- [x] El Profesor también inicia sesión. ¿Es obligatorio? Si fuera así, la relación no es extend sino include.  Aplicar este comentario al resto de casos del profesor.    **MEJORADO PERO NO BIEN: las relaciones include y extends son entre casos de uso; vosotros ponéis un include entre el actor, profesor, y el caso de uso, inicio de sesión.  Según vuestro diagrama de casos de usos, el profesor puede iniciar sesión,disponiendo de las mismas funcionalidades que el alumno; además de inicio de sesión, y sin necesidad de realizarla puede publicar noticias.  ¿Es así cómo queréis hacerlo? Según el curso normal es diferente **
- [x] Curso normal: una vez iniciada la sesión hay 5 puntos de extensión (consulta listado noticias, chat ...). No aparece incluido en el curso normal.  **MEJORADO PARCIALMENTE: las extensiones tienen otro formato: P:EXTENSIÓN(nombre caso de uso)**

**CU Recuperar Cuenta** 
- [x] El Profesor no puede recuperar la cuenta?   **REVISION:  NO CORREGIDO EN EL DIAGRAMA. Según vuestro diagrama el profesor no puede recuperar la cuenta, aunque sí lo ponéis en la descripción del caso de uso**
- [x] Precondición: ponéis "introducir un dato de  ...". ¿No sería el primer paso del curso normal? **CORREGIDO**

**CU Registro de Usuario** 
- [x] Descripción: no dar tanto detalles de la información a introducir.
- [x] El Profesor no se registra?  **REVISION: según vuestro diagrama NO, según vuestra descripción sí**
- [ ] Usar palabras como SI, REPETIR para condicionales, bucles.**REVISION: no corregido**
- **REVISION: el nombre del caso de uso no es el mismo en la descripción que en el diagrama**

**CU Consultar Listado de Noticias** 
- [x] Si la precondición es "haber iniciado sesión", el primer paso no puede ser lo mismo, ya que este paso ya se ha realizado.   **REVISION: Corregido**
- [x] Si no hay alternativas poned "Ninguna".  **REVISION: OK. habéis modificado las alternativas**

**CU Chat Alumno** 
- [x] Mismo comentario sobre precondición.   **REVISION: Corregido**

**CU Chat privado alumno-profesor**   **REVISION: Lo habéis eliminado**
- [x] Mismo comentario sobre precondición.

**CU Modificar perfil**    
- [x] Mismo comentario sobre precondición.  **REVISION: Corregido**

**CU Crear Noticia Nueva** 
- [x] Mismo comentario sobre precondición.   **REVISION: Corregido**
- [x] El actor es el profesor.  **REVISION: Corregido**
- [x] Sobra la relación de extensión.  **REVISION: Corregido**

**REVISION:
CU Cuenta bancaria excursiones: la descripción está incompleta + curso normal no veo que los pasos estén bien explicados (¿el profesor tiene que habilitar el pago? ¿el alumno debe esperar a que el profesor habilitar 'pagar'?**

**Comment by vrsanchez99** [comment]
Hemos corregido todos los issues. Vamos a cambiar las capturas de tablas por tablas en html.
