### ISSUE TITLE
Corrección Proyecto. Fase UT2.  Hilos.

### ISSUE THREAD

**Issue by jlr2** [perezrecjorge/proyectopsp-grupo2#6]
- [x]  No habéis estructurado la aplicación en hilos. Sólo habéis definido una clase que hereada de Thread (AlumnosChat).
- [x]   No implementáis modelo productor-consumidor.
- [x]   No usáis los métodos pedidos.

**Comment by perezrecjorge** [comment]
Corregido.

Gracias. Un Saludo.
