### ISSUE TITLE
Corrección proyecto: Fase 2. Codificación

### ISSUE THREAD

**Issue by jlr2** [perezrecjorge/proyectopsp-grupo2#9]
- [ ] Necesito backup de la base de datos que usáis para la aplicación. **Urgente**.  Subir a 'develop' y responder a este issue para saber que ya está subido.

**Comment by perezrecjorge** [comment]
Buenas,

Le he enviado el backup por correo (joseluis.rodriguezrodriguez@iesvalleinclan.es).
De todos modos, en la siguiente fase vamos a implementar BBDD en la nube, por que la usabilidad del apartado de base de datos quedara totalmente resuelto y no habrá este tipo de complicaciones.

Espero respuesta.
Un Saludo.

Att. Jorge Perez.
